### ISSUE TITLE
understanding the regression

### ISSUE THREAD

**Issue by stoeckel4code** [VACILT/student_project#1]
1. I don't get how the coefficients are are depending on more than one variable.
I thought the regression must be  y(a,b)=z0+z1*x1(a,b)+z2*x2(a,b)+ ... + zn*xn(a,b), where zn are the coefficients, which only have one dimension. 

2. How can the unit be "%"?

**Comment by kuchaale** [comment]
1. Regression coefficients are 2D because regressed time-series are 2D+time and regressors are 1D, i.e. y(x,y,t) = z0(x,y) + z1(x,y)*x1(t) + ...
2. Because the regressed time-series are expressed in % in terms of climatology (see [here](https://github.com/kuchaale/X-regression/blob/master/examples/solaris-heppa/solaris_heppa_analysis-script.py#L50)).

**Comment by stoeckel4code** [comment]
1. So the regression is done for every point of (x,y) and the regression is only over the time? Am I right?

2. ok, makes sence.
